### ISSUE TITLE
Usage with other grammar than HTML?

### ISSUE THREAD

**Issue by derwaldgeist** [f/atom-bootstrap3#34]
Is it possible to use this plugin for other grammars than HTML? I am using the Spacebars grammar, since I am developing for Meteor, the snippets are not recognized there.

**Comment by linkleonard** [comment]
I use Bootstrap components in Jinja templates, and it would be nice to be able to utilize this there as well.

**Comment by derwaldgeist** [comment]
Closing this as nothing happened after nearly one year - and I am not using this either :-)
